hotfix(dependency-track): added reports and Storage Account to host UUID files
- added reports for all kind of tests

Signed-off-by: Felipe Rios <felipe.rios.silva@outlook.com>

diff --git a/azure-devops/global/stages/35-management/dependency-track.yaml b/azure-devops/global/stages/35-management/dependency-track.yaml
--- a/azure-devops/global/stages/35-management/dependency-track.yaml
+++ b/azure-devops/global/stages/35-management/dependency-track.yaml
@@ -2,20 +2,41 @@ parameters:
   - name: 'BEFORE_SCRIPT'
     type: 'string'
     default: ''
+  - name: 'UUID_FOLDER'
+    type: 'string'
+    default: '35-management/dependency-track'
 
 steps:
   - script: ${{ parameters.BEFORE_SCRIPT }}
 
-  - task: 'DownloadPipelineArtifact@2'
+  # keep in mind you need STORAGE_ACCOUNT_NAME, STORAGE_CONTAINER_NAME, STORAGE_ACCOUNT_KEY environment variables
+  - task: 'AzureCLI@2'
     inputs:
-      artifactName: 'dependency-track-uuid'
-      targetPath: "$(Pipeline.Workspace)/uuid"
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e
+
+        if [ ! -z "$STORAGE_ACCOUNT_NAME" ]; then
+          mkdir -p $(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}
+          az storage blob download \
+            --account-name $(STORAGE_ACCOUNT_NAME) \
+            --container-name $(STORAGE_CONTAINER_NAME) \
+            --name ${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt \
+            --file $(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt \
+            --account-key $(STORAGE_ACCOUNT_KEY)
+        else
+          echo "STORAGE_ACCOUNT_NAME environment variable not found. Skipping download."
+        fi
     displayName: 'Download Project UUID'
     continueOnError: true
 
   - script: |
-      if [ -f "$(Pipeline.Workspace)/uuid/uuid.txt" ]; then
-        export UUID=$(cat $(Pipeline.Workspace)/uuid/uuid.txt)
+      set -e
+
+      if [ -f "$(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt" ]; then
+        export UUID=$(cat $(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt)
         export REQUEST_CONTENT_TYPE="Content-Type: multipart/form-data"
         export REQUEST_API_KEY="X-Api-Key: $(DEPENDENCY_TRACK_TOKEN)"
         curl --insecure --fail --request 'POST' "$(DEPENDENCY_TRACK_HOST_URL)/api/v1/bom" \
@@ -29,7 +50,9 @@ steps:
     displayName: 'Upload BOM with existing UUID'
 
   - script: |
-      if [ ! -f "$(Pipeline.Workspace)/uuid/uuid.txt" ]; then
+      set -e
+
+      if [ ! -f "$(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt" ]; then
         export REQUEST_CONTENT_TYPE="Content-Type: multipart/form-data"
         export REQUEST_API_KEY="X-Api-Key: $(DEPENDENCY_TRACK_TOKEN)"
         RESPONSE=$(curl --insecure --fail --request 'POST' "$(DEPENDENCY_TRACK_HOST_URL)/api/v1/bom" \
@@ -38,14 +61,27 @@ steps:
           -F "projectVersion=$(cat $(PREFIX)$(REPORT_PATH)/bom.json | jq -r '.metadata.component.version')" \
           -F 'autoCreate=true' -F "bom=@$(PREFIX)$(REPORT_PATH)/bom.json")
         UUID=$(echo $RESPONSE | jq -r '.token')
-        echo $UUID > $(Pipeline.Workspace)/uuid/uuid.txt
+        mkdir -p $(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}
+        echo $UUID > $(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt
       fi
     displayName: 'Create new project and upload BOM'
 
-  - task: 'PublishPipelineArtifact@1'
+  - task: 'AzureCLI@2'
     inputs:
-      targetPath: "$(Pipeline.Workspace)/uuid"
-      artifactName: 'dependency-track-uuid'
-      publishLocation: 'pipeline'
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e
+
+        if [ ! -z "$STORAGE_ACCOUNT_NAME" ]; then
+          az storage blob upload \
+            --account-name $(STORAGE_ACCOUNT_NAME) \
+            --container-name $(STORAGE_CONTAINER_NAME) \
+            --name ${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt \
+            --file $(Pipeline.Workspace)/${{ parameters.UUID_FOLDER }}/$(Build.DefinitionName).txt \
+            --account-key $(STORAGE_ACCOUNT_KEY)
+        else
+          echo "STORAGE_ACCOUNT_NAME environment variable not found. Skipping upload."
+        fi
     displayName: 'Publish Project UUID'
-    condition: succeededOrFailed()
