wip
Signed-off-by: Kalil Teixeira Ventura Monteiro <kalilventur@gmail.com>

diff --git a/azure-devops/global/abstracts/database.yaml b/azure-devops/global/abstracts/database.yaml
--- a/azure-devops/global/abstracts/database.yaml
+++ b/azure-devops/global/abstracts/database.yaml
@@ -13,25 +13,27 @@ parameters:
     type: 'string'
   - name: SEEDERS_CACHE
     type: 'string'
+  # - name: CONNECTION_STRING
+  #   type: 'string'
+  #   default: ''
+  # - name: DATABASE_SERVER_NAME
+  #   type: 'string'
+  #   default: ''
+
 
 steps:
   - script: |
       set -e
-      echo "Pipeline Firewall name: ${{ parameters.PIPELINE_FIREWALL_NAME }}"
-      echo "Resource Group name: ${{ parameters.RESOURCE_GROUP_NAME }}"
-      echo "Environment Variable: ${{ parameters.ENVIRONMENT }}"
-      echo "AZM_SERVICE_CONNECTION Variable: ${{ parameters.AZM_SERVICE_CONNECTION }}"
-      echo "MIGRATIONS_CACHE Variable: ${{ parameters.MIGRATIONS_CACHE }}"
-      echo "SEEDERS_CACHE Variable: ${{ parameters.SEEDERS_CACHE }}"
 
-      PORT=$(echo "${{ parameters.OUTPUTS }}" | jq -r '.databaseServerPort.value')
-      HOST=$(echo "${{ parameters.OUTPUTS }}" | jq -r '.databaseServerHost.value')
-      USER=$(echo "${{ parameters.OUTPUTS }}" | jq -r '.databaseServerUsername.value')
-      PASSWORD=$(echo "${{ parameters.OUTPUTS }}" | jq -r '.databaseServerPassword.value')
-      DBNAME=$(echo "${{ parameters.OUTPUTS }}" | jq -r '.databaseName.value')
-      SSL=$(echo "${{ parameters.OUTPUTS }}" | jq -r '.databaseServerSSL.value')
-
+      PORT=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseServerPort.value')
+      HOST=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseServerHost.value')
+      USER=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseServerUsername.value')
+      PASSWORD=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseServerPassword.value')
+      DBNAME=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseName.value')
+      SSL=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseServerSSL.value')
       CONNECTION_STRING="host=$HOST port=$PORT user=$USER password=$PASSWORD dbname=$DBNAME sslmode=$SSL"
+
+      DATABASE_SERVER_NAME=$(echo $AZURE_DEPLOY_OUTPUTS | jq -r '.databaseServerName.value')
 
       echo "PORT: $PORT"
       echo "HOST: $HOST"
@@ -40,148 +42,139 @@ steps:
       echo "DBNAME: $DBNAME"
       echo "SSL: $SSL"
       echo "CONNECTION_STRING: $CONNECTION_STRING"
-    displayName: 'Print variables'
+      echo "DATABASE_SERVER_NAME: $DATABASE_SERVER_NAME"
 
-  # - task: 'AzureCLI@2'
-  #   displayName: 'Check if Database Exists'
-  #   inputs:
-  #     azureSubscription: "$(AZM_SERVICE_CONNECTION)"
-  #     scriptType: 'bash'
-  #     scriptLocation: 'inlineScript'
-  #     inlineScript: |
-  #       DATABASE_SERVER_NAME=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerName.value')
+      echo "##vso[task.setvariable variable=CONNECTION_STRING]$CONNECTION_STRING"
+      echo "##vso[task.setvariable variable=DATABASE_SERVER_NAME]$DATABASE_SERVER_NAME"
+    displayName: 'Extract and Set Variables'
+    env:
+      AZURE_DEPLOY_OUTPUTS: ${{ parameters.OUTPUTS }}
 
-  #       echo "DATABASE_SERVER_NAME: $DATABASE_SERVER_NAME"
+  - task: 'AzureCLI@2'
+    displayName: 'Check if Database Exists'
+    inputs:
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        DATABASE_SERVER_NAME=${{ parameters.DATABASE_SERVER_NAME}}
+        echo "DATABASE_SERVER_NAME: $DATABASE_SERVER_NAME"
 
-  #       if [[ -z "$DATABASE_SERVER_NAME" || "$DATABASE_SERVER_NAME" == "null" ]]; then
-  #         echo "Invalid database server name: $DATABASE_SERVER_NAME"
-  #         echo "##vso[task.setvariable variable=DB_EXISTS]false"
-  #         exit 0
-  #       fi
-  #       dbExists=$(az postgres flexible-server show --resource-group "${{ parameters.RESOURCE_GROUP_NAME }}" --name "$DATABASE_SERVER_NAME" --query "name" --output tsv 2>/dev/null || echo "null")
-  #       echo "database exists: $dbExists"
-  #       if [[ "$dbExists" != "null" ]]; then
-  #         echo "##vso[task.setvariable variable=DB_EXISTS]true"
-  #       else
-  #         echo "##vso[task.setvariable variable=DB_EXISTS]false"
-  #       fi
+        if [[ -z "$DATABASE_SERVER_NAME" || "$DATABASE_SERVER_NAME" == "null" ]]; then
+          echo "Invalid database server name: $DATABASE_SERVER_NAME"
+          echo "##vso[task.setvariable variable=DB_EXISTS]false"
+          exit 0
+        fi
+        dbExists=$(az postgres flexible-server show --resource-group "${{ parameters.RESOURCE_GROUP_NAME }}" --name "$DATABASE_SERVER_NAME" --query "name" --output tsv 2>/dev/null || echo "null")
+        echo "database exists: $dbExists"
+        if [[ "$dbExists" != "null" ]]; then
+          echo "##vso[task.setvariable variable=DB_EXISTS]true"
+        else
+          echo "##vso[task.setvariable variable=DB_EXISTS]false"
+        fi
 
-  # - task: 'AzureCLI@2'
-  #   displayName: 'Create Flexible Firewall Rule to execute migrations and seeders'
-  #   condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
-  #   inputs:
-  #     azureSubscription: "$(AZM_SERVICE_CONNECTION)"
-  #     scriptType: 'bash'
-  #     scriptLocation: 'inlineScript'
-  #     inlineScript: |
-  #       set -e
+  - task: 'AzureCLI@2'
+    displayName: 'Create Flexible Firewall Rule to execute migrations and seeders'
+    condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
+    inputs:
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e
 
-  #       DATABASE_SERVER_NAME=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerName.value')
-  #       echo $DATABASE_SERVER_NAME
+        DATABASE_SERVER_NAME=${{ parameters.DATABASE_SERVER_NAME}}
+        echo $DATABASE_SERVER_NAME
 
-  #       PIPELINE_IP=$(curl -s ifconfig.me/ip)
-  #       az postgres flexible-server firewall-rule create \
-  #           --resource-group ""${{ parameters.RESOURCE_GROUP_NAME }}" \
-  #           --name "$DATABASE_SERVER_NAME" \
-  #           --rule-name "${{ parameters.PIPELINE_FIREWALL_NAME }}" \
-  #           --start-ip-address "$PIPELINE_IP"
-  # - script: |
-  #     set -e
-  #     PORT=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerPort.value')
-  #     HOST=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerHost.value')
-  #     USER=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerUsername.value')
-  #     PASSWORD=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerPassword.value')
-  #     DBNAME=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseName.value')
-  #     SSL=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerSSL.value')
-  #     CONNECTION_STRING="host=$HOST port=$PORT user=$USER password=$PASSWORD dbname=$DBNAME sslmode=$SSL"
-  #     echo "##vso[task.setvariable variable=CONNECTION_STRING]$CONNECTION_STRING"
-  #     echo $CONNECTION_STRING
-  #   displayName: 'Set Database Connection String'
-  #   condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
+        PIPELINE_IP=$(curl -s ifconfig.me/ip)
+        az postgres flexible-server firewall-rule create \
+            --resource-group ""${{ parameters.RESOURCE_GROUP_NAME }}" \
+            --name "$DATABASE_SERVER_NAME" \
+            --rule-name "${{ parameters.PIPELINE_FIREWALL_NAME }}" \
+            --start-ip-address "$PIPELINE_IP"
 
-  # - script: |
-  #     set -e
-  #     table_hash=$(psql "$(CONNECTION_STRING)" -t -c \
-  #     "SELECT md5(string_agg(concat_ws('|', version_id::text, is_applied::text), ',' ORDER BY id)) AS table_hash FROM goose_db_version;")
-  #     table_hash=$(echo "$table_hash" | xargs)
-  #     echo "table_hash: $table_hash"
-  #     echo "##vso[task.setvariable variable=GOOSE_TABLE_HASH]$table_hash"
-  #   displayName: 'Set Goose Table Hash variable'
-  #   condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
-  #   continueOnError: true
+  - script: |
+      set -e
+      table_hash=$(psql "${{ parameters.CONNECTION_STRING }}" -t -c \
+      "SELECT md5(string_agg(concat_ws('|', version_id::text, is_applied::text), ',' ORDER BY id)) AS table_hash FROM goose_db_version;")
+      table_hash=$(echo "$table_hash" | xargs)
+      echo "table_hash: $table_hash"
+      echo "##vso[task.setvariable variable=GOOSE_TABLE_HASH]$table_hash"
+    displayName: 'Set Goose Table Hash variable'
+    condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
+    continueOnError: true
 
-  # - task: 'Cache@2'
-  #   displayName: 'Cache for Migrations'
-  #   condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
-  #   inputs:
-  #     key: "$(Agent.JobName)|$(ENVIRONMENT)|$(GOOSE_TABLE_HASH)|db/migrations/*.sql"
-  #     path: "$(MIGRATIONS_CACHE)"
-  #     cacheHitVar: 'MIGRATIONS_CACHE_HIT'
-  #   continueOnError: true
+  - task: 'Cache@2'
+    displayName: 'Cache for Migrations'
+    condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
+    inputs:
+      key: "$(Agent.JobName)|$(ENVIRONMENT)|$(GOOSE_TABLE_HASH)|db/migrations/*.sql"
+      path: "$(MIGRATIONS_CACHE)"
+      cacheHitVar: 'MIGRATIONS_CACHE_HIT'
+    continueOnError: true
 
-  # - task: 'Cache@2'
-  #   displayName: 'Cache for Seeders'
-  #   condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
-  #   inputs:
-  #     key: "$(Agent.JobName)|$(ENVIRONMENT)|$(GOOSE_TABLE_HASH)|db/seeders/*.sql"
-  #     path: "$(SEEDERS_CACHE)"
-  #     cacheHitVar: 'SEEDERS_CACHE_HIT'
-  #   continueOnError: true
+  - task: 'Cache@2'
+    displayName: 'Cache for Seeders'
+    condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
+    inputs:
+      key: "$(Agent.JobName)|$(ENVIRONMENT)|$(GOOSE_TABLE_HASH)|db/seeders/*.sql"
+      path: "$(SEEDERS_CACHE)"
+      cacheHitVar: 'SEEDERS_CACHE_HIT'
+    continueOnError: true
 
-  # - task: 'AzureCLI@2'
-  #   inputs:
-  #     condition: and(succeeded(), eq(variables['MIGRATIONS_CACHE_HIT'], 'false'))
-  #     azureSubscription: "$(AZM_SERVICE_CONNECTION)"
-  #     scriptType: 'bash'
-  #     scriptLocation: 'inlineScript'
-  #     inlineScript: |
-  #       set -e
-  #       # TODO: move this "IF" to a file and (or) use an Azure resource to create a condition
-  #       if grep -r 'goose' db/migrations/*.sql; then
-  #         go install github.com/pressly/goose/v3/cmd/goose@v3.17.0
-  #         $(go env GOPATH)/bin/goose -dir db/migrations postgres "$(CONNECTION_STRING)" up
-  #       else
-  #         echo "No Goose migration files found. Skipping Goose installation and migration."
-  #       fi
-  #     displayName: 'Execute Migrations'
+  - task: 'AzureCLI@2'
+    inputs:
+      condition: and(succeeded(), eq(variables['MIGRATIONS_CACHE_HIT'], 'false'))
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e
+        # TODO: move this "IF" to a file and (or) use an Azure resource to create a condition
+        if grep -r 'goose' db/migrations/*.sql; then
+          go install github.com/pressly/goose/v3/cmd/goose@v3.17.0
+          $(go env GOPATH)/bin/goose -dir db/migrations postgres "${{ parameters.CONNECTION_STRING }}" up
+        else
+          echo "No Goose migration files found. Skipping Goose installation and migration."
+        fi
+      displayName: 'Execute Migrations'
 
-  # - task: 'AzureCLI@2'
-  #   inputs:
-  #     condition: and(succeeded(), eq(variables['SEEDERS_CACHE_HIT'], 'false'))
-  #     azureSubscription: "$(AZM_SERVICE_CONNECTION)"
-  #     scriptType: 'bash'
-  #     scriptLocation: 'inlineScript'
-  #     inlineScript: |
-  #       set -e
-  #       echo "CONNECTION_STRING: $CONNECTION_STRING"
-  #       if grep -r 'goose' db/seeders/*.sql; then
-  #         go install github.com/pressly/goose/v3/cmd/goose@v3.22.1
-  #         for dir in "" "dev" "prod"; do
-  #             if [ -z "$dir" ] || [ "$ENVIRONMENT" == "$dir" ]; then
-  #               dir_path="db/seeders/$dir"
-  #               dir_path=${dir_path%/}
-  #               if grep -q 'goose' $dir_path/*.sql; then
-  #                   $(go env GOPATH)/bin/goose -dir $dir_path postgres "$(CONNECTION_STRING)" up
-  #               fi
-  #             fi
-  #         done
-  #       else
-  #           echo "No Goose seed files found. Skipping seed"
-  #       fi
-  #     displayName: 'Execute Seeders'
+  - task: 'AzureCLI@2'
+    inputs:
+      condition: and(succeeded(), eq(variables['SEEDERS_CACHE_HIT'], 'false'))
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e
+        echo "CONNECTION_STRING: ${{ parameters.CONNECTION_STRING }}"
+        if grep -r 'goose' db/seeders/*.sql; then
+          go install github.com/pressly/goose/v3/cmd/goose@v3.22.1
+          for dir in "" "dev" "prod"; do
+              if [ -z "$dir" ] || [ "$ENVIRONMENT" == "$dir" ]; then
+                dir_path="db/seeders/$dir"
+                dir_path=${dir_path%/}
+                if grep -q 'goose' $dir_path/*.sql; then
+                    $(go env GOPATH)/bin/goose -dir $dir_path postgres "${{ parameters.CONNECTION_STRING }}" up
+                fi
+              fi
+          done
+        else
+            echo "No Goose seed files found. Skipping seed"
+        fi
+      displayName: 'Execute Seeders'
 
-  # - task: 'AzureCLI@2'
-  #   displayName: 'Delete Flexible Firewall Rule to execute migrations and seeders'
-  #   condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
-  #   inputs:
-  #     azureSubscription: "$(AZM_SERVICE_CONNECTION)"
-  #     scriptType: 'bash'
-  #     scriptLocation: 'inlineScript'
-  #     inlineScript: |
-  #       set -e
-  #       DATABASE_SERVER_NAME=$(echo ${{ parameters.OUTPUTS }} | jq -r '.databaseServerName.value')
-  #       PIPELINE_IP=$(curl -s ifconfig.me/ip)
-  #       az postgres flexible-server firewall-rule delete --yes \
-  #         --resource-group "${{ parameters.RESOURCE_GROUP_NAME }}" \
-  #         --name "$DATABASE_SERVER_NAME" \
-  #         --rule-name "${{ parameters.PIPELINE_FIREWALL_NAME }}"
+  - task: 'AzureCLI@2'
+    displayName: 'Delete Flexible Firewall Rule to execute migrations and seeders'
+    condition: and(succeeded(), eq(variables['DB_EXISTS'], 'true'))
+    inputs:
+      azureSubscription: "$(AZM_SERVICE_CONNECTION)"
+      scriptType: 'bash'
+      scriptLocation: 'inlineScript'
+      inlineScript: |
+        set -e
+        PIPELINE_IP=$(curl -s ifconfig.me/ip)
+        az postgres flexible-server firewall-rule delete --yes \
+          --resource-group "${{ parameters.RESOURCE_GROUP_NAME }}" \
+          --name "${{ parameters.DATABASE_SERVER_NAME}}" \
+          --rule-name "${{ parameters.PIPELINE_FIREWALL_NAME }}"
